version: '3.8'
services:
  db:
    image: postgres:15-alpine
    container_name: nextstrap_test_db
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: nextstrap_test
    volumes:
      - nextstrap_test_db:/var/lib/postgresql/data
    # Map default Postgres port for test environment
    ports:
      - "5432:5432"

  mailhog:
    container_name: nextstrap_test_mailhog
    image: mailhog/mailhog:latest
    platform: linux/amd64
    restart: unless-stopped
    ports:
      - "1025:1025"  # SMTP
      - "8025:8025"  # Web UI

  test-server:
    image: node:20-bullseye
    container_name: nextstrap_test_server
    working_dir: /app
    volumes:
      - ./:/app
    environment:
      # Use SMTP_URL format for simplified configuration
      SMTP_URL: smtp://mailhog:1025
      EMAIL_FROM: test@example.com
      NODE_ENV: test
    command: >
      sh -c "npm run build && npm run start"
    depends_on:
      - db
      - mailhog

volumes:
  nextstrap_test_db: