name: Port4kMUD CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build_and_test_server:
    name: Build and Test Server
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x] # Test against Node.js 20.x

    defaults:
      run:
        working-directory: ./server

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'yarn' # Cache yarn dependencies
        cache-dependency-path: './server/yarn.lock'

    - name: Install dependencies
      run: yarn install --frozen-lockfile

    - name: Run linters
      run: yarn lint # Ensure code style and quality

    - name: Build project
      run: yarn build

    - name: Run tests
      run: yarn test
      env:
        CI: true # Often useful to indicate running in a CI environment

  build_mud:
    name: Build MUD
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./mud

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install build dependencies
      run: sudo apt-get update && sudo apt-get install -y build-essential

    - name: Configure MUD
      run: ./configure

    - name: Build MUD
      run: cd src && make

    - name: Verify build artifacts
      run: |
        if [ ! -f "bin/circle" ]; then
          echo "MUD build failed: bin/circle not found"
          exit 1
        fi
